import { DependencyListV2 } from "./types";

// OLD CURRICULUM 2018

export const cheDepOld: DependencyListV2 = [
  {
    // B - 1yr - 1sem - oc
    subjects: [
      {
        subjectCode: "EBMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBMath 1102",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 23,
  },
  // B - 1yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "EBMath 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBEngg 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE1a(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE2B(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 26,
  },
  // B - 2yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE Eng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 12",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 3a",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 22,
  },
  // B - 2yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: [],
        coRequisites: ["EMath 1101"],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 1202",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 13",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 22,
  },
  // B - 3yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201", "EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2101",
        prerequisites: ["ChE 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2102",
        prerequisites: ["Engg 1001", "ChE 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1025",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "EE 2121",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 25,
  },
  // B - 3yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1021",
        prerequisites: ["ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Che 2201",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2202",
        prerequisites: ["ChE 2102", "EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2203",
        prerequisites: ["ChE 2102", "EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2204",
        prerequisites: ["ChE 2101", "ChE 2102"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 21,
  },
  // B - 4yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3106",
        prerequisites: ["Engg 1002"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3107",
        prerequisites: ["ChE 2202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3108",
        prerequisites: ["ChE 1103"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3109",
        prerequisites: ["ChE 2203", "ChE 2102"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3110",
        prerequisites: ["ChE 2203", "ChE 2102", "EMath 1202", "GEEng 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4111",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "ChE 2101"],
        name: "Food Processing Technologies",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4115",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1018"],
        name: "Fundamental Principles of Packaging",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4118",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1019"],
        name: "Air Pollution Control",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4121",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "ChE 2101"],
        name: "Introduction to Petroleum Engineering",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4124",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1019"],
        name: "Renewable Energy Technologies",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 18,
  },
  // B - 4yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "ChE 3206",
        prerequisites: ["ChE 2202", "ChE 3107"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3207",
        prerequisites: ["ChE 2202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3208",
        prerequisites: ["ChE 3107", "ChE 2201", "ChE 3108"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3209",
        prerequisites: ["ChE 3107", "ChE 3109"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3210",
        prerequisites: ["ChE 3106", "ChE 2201", "ChE 3109"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4112",
        referenceCode: "Che TE 2",
        prerequisites: ["ChE TE 1", "Che 2101"],
        coRequisites: [],
        name: "Pharmaceuticals",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4116",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 4115"],
        coRequisites: [],
        name: "Packaging Materials & Components 1",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4119",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 4203"],
        coRequisites: [],
        name: "Solid Waste Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4122",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 2101"],
        coRequisites: [],
        name: "Polymer Engineering",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4124",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "Engg 1019"],
        coRequisites: [],
        name: "Energy Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "Engg 1028",
        prerequisites: ["Engg 1032"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 23,
  },
  // B - 4yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "ChE 4000",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 4,
    creditUnits: 3,
  },
  // B - 5yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "ChE 4105",
        prerequisites: ["ChE 3206"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4106",
        prerequisites: ["ChE 3207", "ChE 3208", "ChE 3209"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4107",
        prerequisites: ["ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4108",
        prerequisites: ["GESocSci 5"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4109",
        prerequisites: ["ChE 3208", "ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4110",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "ChE 4113",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 2101"],
        coRequisites: [],
        name: "Soaps and Detergents",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4117",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 4116"],
        coRequisites: [],
        name: "Packaging Materials & Components 2",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4120",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 4203"],
        coRequisites: [],
        name: "Hazardous Waste Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4132",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 2101"],
        coRequisites: [],
        name: "Plastics Technology",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4126",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "Engg 1019"],
        coRequisites: [],
        name: "Green Boiler Technology",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4100",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 5,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 5,
    creditUnits: 14,
  },
  // B - 5yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "ChE 4211",
        prerequisites: ["ChE 3107", "ChE 3208"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4212",
        prerequisites: ["ChE 4106", "Engg 1025"],
        coRequisites: ["ChE 4214"],
        type: "regular",
      },
      {
        subjectCode: "ChE 4213",
        prerequisites: ["ChE 3207", "Engg 1019"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4214",
        prerequisites: ["ChE 2201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4200",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 5,
        type: "regular",
      },
      {
        subjectCode: "CELit1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 5,
    creditUnits: 14,
  },

  // R - 1yr - 1sem - oc

  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 23,
  },

  // R - 1yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 1202",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 26,
  },

  // R - 1yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 1,
    creditUnits: 9,
  },

  // R - 2yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201", "EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2101",
        prerequisites: ["Che 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2102",
        prerequisites: ["Engg 1001", "ChE 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 12",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 3a",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 24,
  },
  // R - 2yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1021",
        prerequisites: ["ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2201",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2202",
        prerequisites: ["ChE 2102", "EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2203",
        prerequisites: ["ChE 2102", "EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2204",
        prerequisites: ["ChE 2101", "ChE 2102"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 13",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 23,
  },
  // R - 2yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },
  // R - 3yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "EE 2121",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3106",
        prerequisites: ["Engg 1002"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3107",
        prerequisites: ["ChE 2202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3108",
        prerequisites: ["ChE 2203"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3109",
        prerequisites: ["ChE 2203", "ChE 2102"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3110",
        prerequisites: ["ChE 2203", "ChE 2102", "EMath 1202", "GE Eng 1"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 22,
  },
  // R - 3yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "ChE 3206",
        prerequisites: ["ChE 2202", "ChE 3107"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3207",
        prerequisites: ["ChE 2202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3208",
        prerequisites: ["ChE 3107", "ChE 2201", "ChE 3108"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3209",
        prerequisites: ["ChE 3107", "ChE 3109"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3210",
        prerequisites: ["ChE 2201", "ChE 3106", "ChE 3109"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3211",
        prerequisites: ["ChE 3110"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4111",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "ChE 2101"],
        name: "Food Processing Technologies",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4115",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1018"],
        name: "Fundamental Principles of Packaging",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4118",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1019"],
        name: "Air Pollution Control",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4121",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "ChE 2101"],
        name: "Introduction to Petroleum Engineering",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4124",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1019"],
        name: "Renewable Energy Technologies",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 24,
  },
  // R - 3yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "ChE 4000",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 3,
    creditUnits: 3,
  },
  // R - 4yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4105",
        prerequisites: ["ChE 3206"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4106",
        prerequisites: ["ChE 3207", "ChE 3208", "ChE 3209"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4107",
        prerequisites: ["ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4108",
        prerequisites: ["GESocSci 5"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4109",
        prerequisites: ["ChE 3208", "ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4110",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "ChE 4112",
        referenceCode: "Che TE 2",
        prerequisites: ["ChE TE 1", "Che 2101"],
        coRequisites: [],
        name: "Pharmaceuticals",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4116",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 4115"],
        coRequisites: [],
        name: "Packaging Materials & Components 1",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4119",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 4203"],
        coRequisites: [],
        name: "Solid Waste Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4122",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 2101"],
        coRequisites: [],
        name: "Polymer Engineering",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4124",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "Engg 1019"],
        coRequisites: [],
        name: "Energy Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4100",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 16,
  },
  // R - 4yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1028",
        prerequisites: ["Engg 1032"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4211",
        prerequisites: ["ChE 3107", "ChE 3208"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4212",
        prerequisites: ["ChE 4106", "Engg 1035"],
        coRequisites: ["ChE 4214"],
        type: "regular",
      },
      {
        subjectCode: "ChE 4213",
        prerequisites: ["ChE 3207", "Engg 1019"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4214",
        prerequisites: ["ChE 2201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4113",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 2101"],
        coRequisites: [],
        name: "Soaps and Detergents",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4117",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 4116"],
        coRequisites: [],
        name: "Packaging Materials & Components 2",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4120",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 4203"],
        coRequisites: [],
        name: "Hazardous Waste Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4132",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 2101"],
        coRequisites: [],
        name: "Plastics Technology",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4126",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "Engg 1019"],
        coRequisites: [],
        name: "Green Boiler Technology",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4200",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CELit1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 20,
  },
];

// NEW CURRICULUM
export const cheDepNew: DependencyListV2 = [
  {
    // B - 1yr - 1sem - nc
    subjects: [
      {
        subjectCode: "EBMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBMath 1102",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 23,
  },
  // B - 1yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "EBMath 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBEngg 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: ["NSTP1-CWTS"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: ["NSTP1-LTS"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: ["NSTP1-ROTC"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 W",
        prerequisites: ["PATHFit1 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 M",
        prerequisites: ["PATHFit1 M"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 26,
  },
  // B - 2yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE Eng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 W",
        prerequisites: ["PATHFit 2 W", "PATHFit1 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 M",
        prerequisites: ["PATHFit 2 M", "PATHFit1 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 22,
  },
  // B - 2yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: [],
        coRequisites: ["EMath 1101"],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 1202",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CETech 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 22,
  },
  // B - 3yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2101",
        prerequisites: ["ChE 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2102",
        prerequisites: ["Engg 1001", "ChE 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1025",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "EE 2121",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 25,
  },
  // B - 3yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1021",
        prerequisites: ["ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Che 2201",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2202",
        prerequisites: ["ChE 2102", "EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2203",
        prerequisites: ["ChE 2102", "EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2204",
        prerequisites: ["ChE 2101", "ChE 2102"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 21,
  },
  // B - 4yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3106",
        prerequisites: ["Engg 1002"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3107",
        prerequisites: ["ChE 2202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3108",
        prerequisites: ["ChE 2203"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3109",
        prerequisites: ["ChE 2203", "ChE 2102"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3110",
        prerequisites: ["ChE 2203", "ChE 2102", "EMath 1202", "GEEng 1"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 15,
  },
  // B - 4yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "ChE 3206",
        prerequisites: ["ChE 2202", "ChE 3107"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3207",
        prerequisites: ["ChE 2202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3208",
        prerequisites: ["ChE 3107", "ChE 2201", "ChE 3108"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3209",
        prerequisites: ["ChE 3107", "ChE 3109"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3210",
        prerequisites: ["ChE 3106", "ChE 2201", "ChE 3109"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4111",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "ChE 2101"],
        name: "Food Processing Technologies",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4115",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1018"],
        name: "Fundamental Principles of Packaging",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4118",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1019"],
        name: "Air Pollution Control",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4121",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "ChE 2101"],
        name: "Introduction to Petroleum Engineering",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4124",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1019"],
        name: "Renewable Energy Technologies",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 21,
  },
  // B - 4yr - summer - nc
  {
    subjects: [
      {
        subjectCode: "Engg 1028",
        prerequisites: ["Engg 1032"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 4,
    creditUnits: 3,
  },
  // B - 5yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "ChE 4105",
        prerequisites: ["ChE 3206"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4106",
        prerequisites: ["ChE 3207", "ChE 3208", "ChE 3209"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4107",
        prerequisites: ["ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4108",
        prerequisites: ["GESocSci 5"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4109",
        prerequisites: ["ChE 3208", "ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4110",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "ChE 4112",
        referenceCode: "Che TE 2",
        prerequisites: ["ChE TE 1", "Che 2101"],
        coRequisites: [],
        name: "Pharmaceuticals",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4116",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 4115"],
        coRequisites: [],
        name: "Packaging Materials & Components 1",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4119",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 4203"],
        coRequisites: [],
        name: "Solid Waste Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4122",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 2101"],
        coRequisites: [],
        name: "Polymer Engineering",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4124",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "Engg 1019"],
        coRequisites: [],
        name: "Energy Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4100",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 5,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 5,
    creditUnits: 14,
  },
  // B - 5yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "ChE 4211",
        prerequisites: ["ChE 3107", "ChE 3208"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4212",
        prerequisites: ["ChE 4106", "Engg 1025"],
        coRequisites: ["ChE 4214"],
        type: "regular",
      },
      {
        subjectCode: "ChE 4213",
        prerequisites: ["ChE 3207", "Engg 1019"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4214",
        prerequisites: ["ChE 2201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4200",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 5,
        type: "regular",
      },
      {
        subjectCode: "CELit1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4113",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 2101"],
        coRequisites: [],
        name: "Soaps and Detergents",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4117",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 4116"],
        coRequisites: [],
        name: "Packaging Materials & Components 2",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4120",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 4203"],
        coRequisites: [],
        name: "Hazardous Waste Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4132",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 2101"],
        coRequisites: [],
        name: "Plastics Technology",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4126",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "Engg 1019"],
        coRequisites: [],
        name: "Green Boiler Technology",
        units: 3,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 5,
    creditUnits: 17,
  },
  // B - 5yr - summer - nc
  {
    subjects: [
      {
        subjectCode: "ChE 4000",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 5,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 5,
    creditUnits: 3,
  },

  // R - 1yr - 1sem - nc

  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 23,
  },

  // R - 1yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 1202",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 W",
        prerequisites: ["PATHFit1 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 M",
        prerequisites: ["PATHFit1 M"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 26,
  },

  // R - 1yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 1,
    creditUnits: 9,
  },

  // R - 2yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2101",
        prerequisites: ["Che 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2102",
        prerequisites: ["Engg 1001", "ChE 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 24,
  },
  // R - 2yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1021",
        prerequisites: ["ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2201",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2202",
        prerequisites: ["ChE 2102", "EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2203",
        prerequisites: ["ChE 2102", "EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 2204",
        prerequisites: ["ChE 2101", "ChE 2102"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CETech 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 23,
  },
  // R - 2yr - summer - nc
  {
    subjects: [
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },

  // R - 3yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "EE 2121",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3106",
        prerequisites: ["Engg 1002"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3107",
        prerequisites: ["ChE 2202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3108",
        prerequisites: ["ChE 2203"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3109",
        prerequisites: ["ChE 2203", "ChE 2102"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3110",
        prerequisites: ["ChE 2203", "ChE 2102", "EMath 1202", "GE Eng 1"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 19,
  },
  // R - 3yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3206",
        prerequisites: ["ChE 2202", "ChE 3107"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3207",
        prerequisites: ["ChE 2202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3208",
        prerequisites: ["ChE 3107", "ChE 2201", "ChE 3108"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3208",
        prerequisites: ["ChE 3107", "ChE 3109"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3210",
        prerequisites: ["ChE 2201", "ChE 3106", "ChE 3109"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 3211",
        prerequisites: ["ChE 3110"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4111",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "ChE 2101"],
        name: "Food Processing Technologies",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4115",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1018"],
        name: "Fundamental Principles of Packaging",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4118",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1019"],
        name: "Air Pollution Control",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4121",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "ChE 2101"],
        name: "Introduction to Petroleum Engineering",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "ChE 4124",
        referenceCode: "ChE TE 1",
        prerequisites: ["Engg 1021", "Engg 1019"],
        name: "Renewable Energy Technologies",
        units: 3,
        coRequisites: [],
        type: "elective",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 23,
  },
  // R - 3yr - summer - nc
  {
    subjects: [
      {
        subjectCode: "Engg 1028",
        prerequisites: ["Engg 1032"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 3,
    creditUnits: 3,
  },

  // R - 4yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "ChE 4105",
        prerequisites: ["ChE 3206"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4106",
        prerequisites: ["ChE 3207", "ChE 3208", "ChE 3209"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4107",
        prerequisites: ["ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4108",
        prerequisites: ["GESocSci 5"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4109",
        prerequisites: ["ChE 3208", "ChE 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4110",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "ChE 4112",
        referenceCode: "Che TE 2",
        prerequisites: ["ChE TE 1", "Che 2101"],
        coRequisites: [],
        name: "Pharmaceuticals",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4116",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 4115"],
        coRequisites: [],
        name: "Packaging Materials & Components 1",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4119",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 4203"],
        coRequisites: [],
        name: "Solid Waste Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4122",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "ChE 2101"],
        coRequisites: [],
        name: "Polymer Engineering",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4124",
        referenceCode: "ChE TE 2",
        prerequisites: ["ChE TE 1", "Engg 1019"],
        coRequisites: [],
        name: "Energy Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4100",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 14,
  },
  // R - 4yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "ChE 4211",
        prerequisites: ["ChE 3107", "ChE 3208"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4212",
        prerequisites: ["ChE 4106", "Engg 1035"],
        coRequisites: ["ChE 4214"],
        type: "regular",
      },
      {
        subjectCode: "ChE 4213",
        prerequisites: ["ChE 3207", "Engg 1019"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4214",
        prerequisites: ["ChE 2201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ChE 4113",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 2101"],
        coRequisites: [],
        name: "Soaps and Detergents",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4117",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 4116"],
        coRequisites: [],
        name: "Packaging Materials & Components 2",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4120",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 4203"],
        coRequisites: [],
        name: "Hazardous Waste Management",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4132",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "ChE 2101"],
        coRequisites: [],
        name: "Plastics Technology",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4126",
        referenceCode: "ChE TE 3",
        prerequisites: ["ChE TE 2", "Engg 1019"],
        coRequisites: [],
        name: "Green Boiler Technology",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "ChE 4200",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CELit1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 20,
  },
  // R - 4yr - summer - nc
  {
    subjects: [
      {
        subjectCode: "ChE 4000",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 4,
    creditUnits: 3,
  },
];
