import { DependencyListV2 } from "./types";

// NEW CURRICULUM 2022
export const ceDeptNew: DependencyListV2 = [
  // FIRST YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EBMath 1101",
        prerequisites: [],
        coRequisites: [],
        name: "Algebra and Plane and Spherical Trigonometry",
        units: 5,
        type: "regular",
      },
      {
        subjectCode: "EBMath 1102",
        prerequisites: [],
        coRequisites: [],
        name: "Solid Mensuration and Analytic Geometry",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        name: "Mathematics in the Modern World",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        name: "Science, Technology and Society",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        name: "Civic Welfare Training Services",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        name: "Literary Training Services",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        name: "Reserved Officers' Training Corps",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 W",
        prerequisites: [],
        coRequisites: [],
        name: "Physical Activity Toward Health and Fitniss - Movement Competency Training",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 M",
        prerequisites: [],
        coRequisites: [],
        name: "Physical Activity Toward Health and Fitniss - Movement Competency Training",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Christianity in a Changing Society",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        name: "Student Enhancement Activities for Life I",
        units: 1,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 23,
  },

  //FIRST YEAR - SECOND SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EBMath 1201",
        prerequisites: [],
        coRequisites: [],
        name: "Introduction to Differential and Integral Calculus",
        units: 5,
        type: "regular",
      },
      {
        subjectCode: "EBEngg 1201",
        prerequisites: [],
        coRequisites: [],
        name: "General Physics",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        name: "Understanding Self",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "GESocSci  3",
        prerequisites: [],
        coRequisites: [],
        name: "Life and Works of Rizal",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        name: "Art Appreciation",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: ["NSTP 1"],
        coRequisites: [],
        name: "Civic Welfare Training Services",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: ["NSTP 1"],
        coRequisites: [],
        name: "Literary Training Services",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: ["NSTP 1"],
        coRequisites: [],
        name: "Reserved Officers' Training Corps",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 W",
        prerequisites: ["PATHFit 1 W"],
        coRequisites: [],
        name: "Physical Activity Towards Health and Fitness (PATHFit) - Excercise Based Fitness in a Changing World",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 M",
        prerequisites: ["PATHFit 1 M"],
        coRequisites: [],
        name: "Physical Activity Towards Health and Fitness (PATHFit) - Excercise Based Fitness in a Changing World",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Christian Ethics in a Changing World",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        name: "Student Enhancement Activities for Life II",
        units: 1,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 26,
  },
  // SECOND YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        name: "Calculus I",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        name: "Chemistry for Engineers",
        units: 4,
        type: "regular",
      },
      {
        subjectCode: "Engg 1005",
        prerequisites: [],
        coRequisites: [],
        name: "Engineering Drawings and Plans",
        units: 1,
        type: "regular",
      },
      {
        subjectCode: "CE 1131",
        prerequisites: [],
        coRequisites: [],
        name: "Civil Engineering Orientation",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        name: "Purposive Communication",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        name: "Readings in Philippine History",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        name: "The Contemporary World",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        name: "Physical Activity Towards Health and Fitness (PATHFit) - Dance and Swimming",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        name: "Physical Activity Towards Health and Fitness (PATHFit) - Dance and Swimming",
        units: 2,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 21,
  },
  // SECOND YEAR - SECOND SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        name: "Calculus II",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        name: "Engineering Data Analysis",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        name: "Introduction to Engineering Design",
        units: 1,
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        name: "Physics for Engineers",
        units: 4,
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        name: "Environmental Science and Engineering",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        name: "Ethics",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        name: "Physical Activity Towards Health and Fitness (PATHFit) - Volleyball and Basketball",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        name: "Physical Activity Towards Health and Fitness (PATHFit) - Volleyball and Basketball",
        units: 2,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 19,
  },

  // THIRD YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        name: "Differential Equations",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1013",
        prerequisites: ["EMath 1201", "Engg 1009"],
        coRequisites: [],
        name: "Statics of Rigid Bodies",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1035",
        prerequisites: [],
        coRequisites: [],
        name: "Computer Fundamentals and Programming for CE",
        units: 2,
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "EE 2130",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        name: "Engineering Utilities I",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 2131",
        prerequisites: ["Engg 1005"],
        coRequisites: [],
        name: "Fundamentals of Surveying",
        units: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 2132",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        name: "Geology for Engineers",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "CESocSci 3",
        prerequisites: [],
        coRequisites: [],
        name: "Gender and Society",
        units: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 20,
  },
  // THIRD YEAR - SECOND SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        name: "Linear Algebra",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "Emath 1007",
        prerequisites: [],
        coRequisites: [],
        name: "Computer-Aided Drafting for CE",
        units: 1,
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "Engg 1016",
        prerequisites: ["Engg 1013"],
        coRequisites: [],
        name: "Dynamics of Rigid Bodies",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1017",
        prerequisites: ["Eng 1013"],
        coRequisites: ["Engg 1016"],
        name: "Mechanics of Deformable Bodies for CE",
        units: 4,
        type: "regular",
      },
      {
        subjectCode: "ME 3230",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        name: "Engineering Utilities II",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 2231",
        prerequisites: ["CE 2131"],
        coRequisites: [],
        name: "Highway and Railroad Engineering",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        name: "Great Books",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "CETech 1",
        prerequisites: [],
        coRequisites: [],
        name: "Living in the IT Era",
        units: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 22,
  },

  // FOURTH YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: [],
        coRequisites: [],
        name: "Engineering Economics",
        units: 3,
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3131",
        prerequisites: ["Engg 1005"],
        coRequisites: [],
        name: "Building Systems Design",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3132",
        prerequisites: ["Engg 1017"],
        coRequisites: [],
        name: "Structural Theory",
        units: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 3133",
        prerequisites: [],
        coRequisites: ["Engg 1017"],
        name: "Construction Materials and Testing",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3134",
        prerequisites: ["Engg 1017", "CE 2132"],
        coRequisites: [],
        name: "Geotechnical Engineering (Soil Mechanics)",
        units: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 3135",
        prerequisites: ["Engg 1016", "Engg 1017"],
        coRequisites: [],
        name: "Hydraulics",
        units: 5,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 22,
  },

  // FOURTH YEAR - SECOND SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EMath 3210",
        prerequisites: ["EMath 2102", "Engg 1035"],
        coRequisites: [],
        name: "Numerical Solutions to CE Problems",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        name: "Occupational Safety and Health for Engineers",
        units: 3,
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3231",
        prerequisites: ["CE 3132", "CE 3133"],
        coRequisites: [],
        name: "Principles of Reinforced/Pre-stressed Concrete Design",
        units: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 3232",
        prerequisites: ["CE 3132", "CE 3133"],
        coRequisites: [],
        name: "Principles of Steel Design",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3233",
        prerequisites: [],
        coRequisites: [],
        name: "Construction Methods and Project Management",
        units: 4,
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3234",
        prerequisites: ["CE 3131"],
        coRequisites: [],
        name: "Quantity Surveying",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "CE 3236",
        prerequisites: ["GEEngg 1"],
        coRequisites: [],
        name: "Introduction to CE Project",
        units: 1,
        yearStanding: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 20,
  },
  // FOURTH YEAR - SUMMER - BRIDGING - NC

  {
    subjects: [
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        name: "Technopreneurship 101",
        units: 3,
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 4,
    creditUnits: 3,
  },

  // FIFTH YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        name: "Engineering Management",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "CE 4130",
        prerequisites: [],
        coRequisites: [],
        name: "CE Correlation I",
        units: 2,
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4131",
        prerequisites: ["CE 3236"],
        coRequisites: [],
        name: "CE Project I",
        units: 3,
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4132",
        prerequisites: ["CE 2231"],
        coRequisites: [],
        name: "Principles of Transportation Engineering",
        units: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 4041",
        referenceCode: "CE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Computer Software in Structural Analysis",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4042",
        referenceCode: "CE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Reinforced Concrete Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4043",
        referenceCode: "CE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Structural Design of Towers and Other Vertical Structures",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 5,
    creditUnits: 17,
  },
  // FIFTH YEAR - SECOND SEM - BRIDGING - NC

  {
    subjects: [
      {
        subjectCode: "CE 4230",
        prerequisites: [],
        coRequisites: [],
        name: "CE Correlation II",
        units: 2,
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4231",
        prerequisites: ["CE 4131"],
        coRequisites: [],
        name: "CE Project II",
        units: 2,
        type: "regular",
      },
      {
        subjectCode: "CE 4232",
        prerequisites: [],
        coRequisites: [],
        name: "Hydrology",
        units: 2,
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4233",
        prerequisites: [],
        coRequisites: [],
        name: "Seminars/Colloquia/Field Study",
        units: 1,
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4234",
        prerequisites: [],
        coRequisites: [],
        name: "CE Law, Ethics, and Contracts",
        units: 2,
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4044",
        referenceCode: "CE TE 3",
        prerequisites: [],
        coRequisites: [],
        name: "Earthquake Engineering",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4045",
        referenceCode: "CE TE 3",
        prerequisites: [],
        coRequisites: [],
        name: "Technopreneurship 102",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4046",
        referenceCode: "CE TE 4 ",
        prerequisites: [],
        coRequisites: [],
        name: "Foundation and Retaining Wall Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4047",
        referenceCode: "CE TE 4",
        prerequisites: [],
        coRequisites: [],
        name: "Design of Steel Structures",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4048",
        referenceCode: "CE TE 5",
        prerequisites: [],
        coRequisites: [],
        name: "Prestressed Concrete Design",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4049",
        referenceCode: "SE TE 5",
        prerequisites: [],
        coRequisites: [],
        name: "Technopreneurship 103",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 5,
    creditUnits: 19,
  },

  //FIFTH  YEAR - SUMMER - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "CE 4330",
        prerequisites: [],
        coRequisites: [],
        name: "CE On-the-Job Training",
        units: 3,
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 5,
    creditUnits: 3,
  },

  //FIRST YEAR - FIRST STEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1005",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 1131",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 25,
  },

  // FIRST YEAR - SECOND SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 M",
        prerequisites: ["PATHFit1 M"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 W",
        prerequisites: ["PATHFit1 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 26,
  },
  // FIRST YEAR - SUMMER - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE SocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },

  // SECOND YEAR - FIRST SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1013",
        prerequisites: ["EMath 1201", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1035",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "EE 2130",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2131",
        prerequisites: ["Engg 1005"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2132",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHfit3 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHfit3 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 22,
  },

  // SECOND YEAR - SECOND SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1007",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "Engg 1016",
        prerequisites: ["Engg 1013"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1017",
        prerequisites: ["Engg 1013"],
        coRequisites: ["Engg 1016"],
        type: "regular",
      },
      {
        subjectCode: "ME 2230",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2231",
        prerequisites: ["CE 2131"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CETech 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHfit4 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHfit4 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 24,
  },

  // SECOND YEAR - SUMMER - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE SocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },

  // THIRD YEAR - FIRST SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3131",
        prerequisites: ["Engg 1005"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3132",
        prerequisites: ["Engg 1017"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3133",
        prerequisites: [],
        coRequisites: ["Engg 1017"],
        type: "regular",
      },
      {
        subjectCode: "CE 3134",
        prerequisites: ["Engg 1017", "CE 2132"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3135",
        prerequisites: [],
        coRequisites: ["Engg 1016", "Engg 1017"],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 22,
  },

  // THIRD YEAR - SECOND SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EMath 3210",
        prerequisites: ["EMath 2101", "Engg 1035"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3231",
        prerequisites: ["CE 3132", "CE 3133"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3232",
        prerequisites: ["CE 3132", "CE 3133"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3233",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3234",
        prerequisites: ["CE 3131"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3236",
        prerequisites: ["GEEngg 1"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 20,
  },

  // THIRD YEAR - SUMMER - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 3,
  },

  // FOURTH YEAR - FIRST SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 4130",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4131",
        prerequisites: ["GEEng 1"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4132",
        prerequisites: ["CE 2231"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 4041",
        referenceCode: "CE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Computer Softwares in Structural Analysis",
        units: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4042",
        referenceCode: "CE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Reinforced Concrete Design",
        units: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4043",
        referenceCode: "CE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Structural Design of Towers and Other Vertical Structures",
        units: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 17,
  },

  // FOURTH YEAR - SECOND SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "CE 4230",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4231",
        prerequisites: ["CE 4131"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 4232",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4233",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4234",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4044",
        referenceCode: "CE TE 3",
        prerequisites: [],
        coRequisites: [],
        name: "Earthquake Engineering",
        units: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4045",
        referenceCode: "CE TE 3",
        prerequisites: [],
        coRequisites: [],
        name: "Technopreneurship 102",
        units: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4046",
        referenceCode: "CE TE 4",
        prerequisites: [],
        coRequisites: [],
        name: "Foundation in Retaining Wall Design",
        units: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4047",
        referenceCode: "CE TE 4",
        prerequisites: [],
        coRequisites: [],
        name: "Design of Steel Structures",
        units: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4048",
        referenceCode: "CE TE 5",
        prerequisites: [],
        coRequisites: [],
        name: "Prestressed Concrete Design",
        units: 3,
        type: "elective",
      },
      {
        subjectCode: "CE 4049",
        referenceCode: "CE TE 5",
        prerequisites: [],
        coRequisites: [],
        name: "Technopreneurship 103",
        units: 3,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 19,
  },
  // FOURTH YEAR - SUMMER - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "CE 433O",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 3,
  },
];

////////////////////////////////////////////
// OLD CURRICULUM 2018

export const ceDeptOld: DependencyListV2 = [
  // FIRST YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EBMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBMath 1102",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 23,
  },

  //FIRST YEAR - SECOND SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EBMath 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBEngg 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci  3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 26,
  },

  // SECOND YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1005",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 1131",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 3a",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 21,
  },

  // SECOND YEAR - SECOND SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 19,
  },

  // THIRD YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201", "EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1013",
        prerequisites: ["EMath 1201", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1035",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "EE 3130",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2131",
        prerequisites: ["Engg 1005"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2132",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 12",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 20,
  },
  // THIRD YEAR - SECOND SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Emath 2201",
        prerequisites: ["EMath 2102"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1016",
        prerequisites: ["Engg 1013"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1017",
        prerequisites: ["Eng 1013"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ME 3230",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2231",
        prerequisites: ["CE 2131"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 13",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 21,
  },
  // FOURTH YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3131",
        prerequisites: ["Engg 1005"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3132",
        prerequisites: ["Engg 1017"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3133",
        prerequisites: [],
        coRequisites: ["Engg 1017"],
        type: "regular",
      },
      {
        subjectCode: "CE 3134",
        prerequisites: ["Engg 1017", "CE 2132"],
        coRequisites: ["SE 3131"],
        type: "regular",
      },
      {
        subjectCode: "CE 3135",
        prerequisites: ["Engg 1016", "Engg 1017"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 22,
  },
  // FOURTH YEAR - SECOND SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1007",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3231",
        prerequisites: ["CE 3132", "CE 3133"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3232",
        prerequisites: ["CE 3132", "CE 3133"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3233",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3234",
        prerequisites: ["CE 3131"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3235",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 22,
  },
  // FOURTH YEAR - SUMMER - BRIDGING - OC

  {
    subjects: [
      {
        subjectCode: "CE 3331",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 4,
    creditUnits: 3,
  },

  // FIFTH YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 4130",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4131",
        prerequisites: ["GEEngg 1"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4132",
        prerequisites: ["CE 2231"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 4041",
        referenceCode: "CE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Computer Software in Structural Analysis",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4042",
        referenceCode: "CE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Reinforced Concrete Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4043",
        referenceCode: "CE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Structural Design of Towers and Other Vertical Structures",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4044",
        referenceCode: "CE TE 3",
        prerequisites: [],
        coRequisites: [],
        name: "Earthquake Engineering",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4045",
        referenceCode: "CE TE 3",
        prerequisites: [],
        coRequisites: [],
        name: "Technopreneurship 102",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 5,
    creditUnits: 20,
  },
  // FIFTH YEAR - SECOND SEM - BRIDGING - OC

  {
    subjects: [
      {
        subjectCode: "CE Lit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 4230",
        prerequisites: ["CE 4131"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4231",
        prerequisites: ["CE 4131"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4232",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4233",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4046",
        referenceCode: "CE TE 4 ",
        prerequisites: [],
        coRequisites: [],
        name: "Foundation and Retaining Wall Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4047",
        referenceCode: "CE TE 4",
        prerequisites: [],
        coRequisites: [],
        name: "Design of Steel Structures",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4048",
        referenceCode: "CE TE 5",
        prerequisites: [],
        coRequisites: [],
        name: "Prestressed Concrete Design",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4049",
        referenceCode: "SE TE 5",
        prerequisites: [],
        coRequisites: [],
        name: "Technopreneurship 103",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 5,
    creditUnits: 17,
  },

  //FIRST YEAR - FIRST STEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1005",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 1131",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 25,
  },

  // FIRST YEAR - SECOND SEM - REGULAR - OC

  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 26,
  },
  // FIRST YEAR - SUMMER - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE SocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },

  // SECOND YEAR - FIRST SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1013",
        prerequisites: ["EMath 1201", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1035",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "EE 3130",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2131",
        prerequisites: ["Engg 1005"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2132",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 12",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 3a",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 22,
  },

  // SECOND YEAR - SECOND SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 2201",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1016",
        prerequisites: ["Engg 1013"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1017",
        prerequisites: ["Engg 1013"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ME 3230",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2231",
        prerequisites: ["CE 2131"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 13",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 23,
  },

  // SECOND YEAR - SUMMER - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE SocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },

  // THIRD YEAR - FIRST SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1015",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3131",
        prerequisites: ["Engg 1005"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3132",
        prerequisites: ["Engg 1017"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3133",
        prerequisites: [],
        coRequisites: ["Engg 1017"],
        type: "regular",
      },
      {
        subjectCode: "CE 3134",
        prerequisites: ["Engg 1017", "CE 2132"],
        coRequisites: ["SE 3131"],
        type: "regular",
      },
      {
        subjectCode: "CE 3135",
        prerequisites: [],
        coRequisites: ["Engg 1016", "Engg 1017"],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 22,
  },

  // THIRD YEAR - SECOND SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1007",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3231",
        prerequisites: ["CE 3132", "CE 3133"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3232",
        prerequisites: ["CE 3132", "CE 3133"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3233",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "CE 3234",
        prerequisites: ["CE 3131"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 3235",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 22,
  },

  // THIRD YEAR - SUMMER - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "CE 3331",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 3,
  },

  // FOURTH YEAR - FIRST SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 4130",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4131",
        prerequisites: ["GEEng 1"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4132",
        prerequisites: ["CE 2231"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 4041",
        referenceCode: "CE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Computer Softwares in Structural Analysis",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4042",
        referenceCode: "CE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Reinforced Concrete Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4043",
        referenceCode: "CE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Structural Design of Towers and Other Vertical Structures",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4044",
        referenceCode: "CE TE 3",
        prerequisites: [],
        coRequisites: [],
        name: "Earthquake Engineering",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4045",
        referenceCode: "CE TE 3",
        prerequisites: [],
        coRequisites: [],
        name: "Technopreneurship 102",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 20,
  },

  // FOURTH YEAR - SECOND SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 4230",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4231",
        prerequisites: ["CE 4131"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4232",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4233",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "CE 4046",
        referenceCode: "CE TE 4",
        prerequisites: [],
        coRequisites: [],
        name: "Foundation in Retaining Wall Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4047",
        referenceCode: "CE TE 4",
        prerequisites: [],
        coRequisites: [],
        name: "Design of Steel Structures",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4048",
        referenceCode: "CE TE 5",
        prerequisites: [],
        coRequisites: [],
        name: "Prestressed Concrete Design",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "CE 4049",
        referenceCode: "CE TE 5",
        prerequisites: [],
        coRequisites: [],
        name: "Technopreneurship 103",
        units: 3,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 17,
  },
];
