import { DependencyListV2 } from "./types";

// NEW CURRICULUM 2022-2023
export const eeDeptNew: DependencyListV2 = [
  // FIRST YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EBMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBMath 1102",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 20,
  },
  //FIRST YEAR - SECOND SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EBMath 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBEngg 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CESocSci  3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: ["NSTP 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: ["NSTP 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: ["NSTP 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 W",
        prerequisites: ["PATHFit 1 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 M",
        prerequisites: ["PATHFit 1 M"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 20,
  },
  // SECOND YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1103",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CETech 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 23,
  },
  // SECOND YEAR - SECOND SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 23,
  },
  // THIRD YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1020",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2142",
        prerequisites: ["EMath 1201", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ME 2143",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 23,
  },
  // THIRD YEAR - SECOND SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1014",
        prerequisites: ["Engg 1012"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2241",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2242",
        prerequisites: ["EE 2142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2243",
        prerequisites: ["EMath 2101", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 2241",
        prerequisites: ["EE 2142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ME 2243",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 19,
  },
  // FOURTH YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "EE 3141",
        prerequisites: ["EE 2242", "EE 2243"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3142",
        prerequisites: [],
        coRequisites: ["EE 3141"],
        type: "regular",
      },
      {
        subjectCode: "EE 3143",
        prerequisites: [],
        coRequisites: ["EE 2241"],
        type: "regular",
      },
      {
        subjectCode: "EE 3144",
        prerequisites: ["GESocSci 5"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3145",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3141",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3142",
        prerequisites: [],
        coRequisites: ["ECE 3141"],
        type: "regular",
      },
      {
        subjectCode: "ECE 3143",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 21,
  },
  // FOURTH YEAR - SECOND SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1023",
        prerequisites: ["Engg 1001", "Engg 1014"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "EE 3241",
        prerequisites: ["EE 3141", "EE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3242",
        prerequisites: ["EE 2242"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3243",
        prerequisites: ["EE 2241", "ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3244",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3241",
        prerequisites: ["ECE 3141", "ECE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3242",
        prerequisites: [],
        coRequisites: ["ECE 3241"],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 19,
  },
  // FOURTH YEAR - SUMMER - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 4,
    creditUnits: 3,
  },
  // FIFTH YEAR - FIRST SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EE 4140",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4141",
        prerequisites: ["EE 3144"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4142",
        prerequisites: ["EE 3241"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4143",
        prerequisites: ["EE 3243"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4144",
        prerequisites: ["EE 3244"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4145",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4146",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Planning",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4147",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Protection I (Protective Relaying)",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4148",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Distribution Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4149",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Pneumatics & Process Control",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4150",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Wind and Hydro Energy",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4151",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Projecting Testing Design & Documentation",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 5,
    creditUnits: 17,
  },
  // FIFTH YEAR - SECOND SEM - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EE 4240",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4241",
        prerequisites: ["EE 4141"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4242",
        prerequisites: [],
        coRequisites: ["EE 4241"],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4243",
        prerequisites: [],
        coRequisites: ["EE 4241"],
        type: "regular",
      },
      {
        subjectCode: "EE 4244",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4246",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Operation and Control",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4247",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Protection II (Lighting Protection and Grounding)",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4248",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Transmission Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4249",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Programmable Logic Controllers in Manufacturing & Power System",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4250",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Solar and Biomass Energy",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4251",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Sales and Marketing Management",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 5,
    creditUnits: 14,
  },
  //FIFTH  YEAR - SUMMER - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EE 4341",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        name: "EE On-the-Job Training",
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 5,
    creditUnits: 3,
  },
  //FIRST YEAR - FIRST STEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1103",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Eng 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 22,
  },
  // FIRST YEAR - SECOND SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: ["NSTP 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: ["NSTP 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: ["NSTP 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 M",
        prerequisites: ["PATHFit1 M"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 W",
        prerequisites: ["PATHFit1 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 24,
  },
  // FIRST YEAR - SUMMER - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE SocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },
  // SECOND YEAR - FIRST SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1020",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2142",
        prerequisites: ["EMath 1201", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2143",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ME 2143",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CETech 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHfit3 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHfit3 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 25,
  },
  // SECOND YEAR - SECOND SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1007",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "Engg 1016",
        prerequisites: ["Engg 1013"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1017",
        prerequisites: ["Engg 1013"],
        coRequisites: ["Engg 1016"],
        type: "regular",
      },
      {
        subjectCode: "ME 2230",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CE 2231",
        prerequisites: ["CE 2131"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CETech 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHfit4 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHfit4 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 24,
  },
  // SECOND YEAR - SUMMER - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE SocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },
  // THIRD YEAR - FIRST SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "EE 3141",
        prerequisites: ["EE 2242", "EE 2243"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3142",
        prerequisites: [],
        coRequisites: ["EE 3141"],
        type: "regular",
      },
      {
        subjectCode: "EE 3143",
        prerequisites: ["EE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3144",
        prerequisites: ["GESocSci 5"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3145",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3141",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3142",
        prerequisites: [],
        coRequisites: ["ECE 3141"],
        type: "regular",
      },
      {
        subjectCode: "EE 3143",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 21,
  },
  // THIRD YEAR - SECOND SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1023",
        prerequisites: ["Engg 1001", "Engg 1014"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3241",
        prerequisites: ["EE 3141", "EE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3242",
        prerequisites: ["EE 2242"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3243",
        prerequisites: ["EE 2241", "ECE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3244",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3241",
        prerequisites: ["ECE 3141", "ECE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3242",
        prerequisites: [],
        coRequisites: ["ECE 3241"],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 19,
  },
  // THIRD YEAR - SUMMER - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 3,
  },
  // FOURTH YEAR - FIRST SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EE 4140",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4141",
        prerequisites: ["EE 3144"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4142",
        prerequisites: ["EE 3241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4143",
        prerequisites: ["EE 3243"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4144",
        prerequisites: ["EE 3244"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4145",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4146",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Planning",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4147",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Protection I (Protective Relaying)",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4148",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Distribution Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4149",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Pneumatics & Process Control",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4150",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Wind and Hydro Energy",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4151",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Projecting Testing Design & Documentation",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 17,
  },
  // FOURTH - SECOND SEM - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EE 4240",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4241",
        prerequisites: ["EE 4141"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4242",
        prerequisites: [],
        coRequisites: ["EE 4241"],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4243",
        prerequisites: [],
        coRequisites: ["EE 4241"],
        type: "regular",
      },
      {
        subjectCode: "EE 4244",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4246",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Operation and Control",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4247",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Protection II (Lighting Protection and Grounding)",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4248",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Transmission Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4249",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Programmable Logic Controllers in Manufacturing & Power System",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4250",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Solar and Biomass Energy",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4251",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Sales and Marketing Management",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 14,
  },
  //FIFTH  YEAR - SUMMER - BRIDGING - NC
  {
    subjects: [
      {
        subjectCode: "EE 4341",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        name: "EE On-the-Job Training",
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 5,
    creditUnits: 3,
  },
];

////////////////////////////////////////////
// OLD CURRICULUM 2018

export const eeDeptOld: DependencyListV2 = [
  // FIRST YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EBMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBMath 1102",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 20,
  },
  //FIRST YEAR - SECOND SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EBMath 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBEngg 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 12",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 20,
  },
  // SECOND YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMatg 1103",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 13",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 3a",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 24,
  },
  // SECOND YEAR - SECOND SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 23,
  },
  // THIRD YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201", "EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1020",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2142",
        prerequisites: ["EMath 1201", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ME 2143",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 23,
  },
  // THIRD YEAR - SECOND SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1014",
        prerequisites: ["Engg 1012"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2241",
        prerequisites: ["EMath 21o1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2242",
        prerequisites: ["EE 2142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2234",
        prerequisites: ["EMath 2102", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 2241",
        prerequisites: ["EE 2142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ME 2243",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 19,
  },
  // FOURTH YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "EE 3141",
        prerequisites: ["EE 2242", "EE 2243"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3142",
        prerequisites: [],
        coRequisites: ["EE 3141"],
        type: "regular",
      },
      {
        subjectCode: "EE 3143",
        prerequisites: ["EE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3144",
        prerequisites: ["GESocSci 5"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3145",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3141",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3142",
        prerequisites: [],
        coRequisites: ["ECE 3141"],
        type: "regular",
      },
      {
        subjectCode: "ECE 3143",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 21,
  },
  // FOURTH YEAR - SECOND SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1023",
        prerequisites: ["Engg 1001", "Engg 1014"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3241",
        prerequisites: ["EE 3141", "EE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3242",
        prerequisites: ["EE 2242"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3243",
        prerequisites: ["EE 2241", "ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3244",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3241",
        prerequisites: ["ECE 3141", "ECE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3242",
        prerequisites: [],
        coRequisites: ["ECE 3241"],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 22,
  },
  // FOURTH YEAR - SUMMER - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EE 3341",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 4,
    creditUnits: 3,
  },
  // FIFTH YEAR - FIRST SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EE 4140",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4141",
        prerequisites: ["EE 3144"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4142",
        prerequisites: ["EE 3241"],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4143",
        prerequisites: ["EE 3243"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4144",
        prerequisites: ["EE 3244"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4145",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4146",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Planning",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4147",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Protection I (Protective Relaying)",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4148",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Distribution Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4149",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Pneumatics & Process Control",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4150",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Wind and Hydro Energy",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4151",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Projecting Testing Design & Documentation",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 5,
    creditUnits: 17,
  },
  // FIFTH YEAR - SECOND SEM - BRIDGING - OC
  {
    subjects: [
      {
        subjectCode: "EE 4240",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4241",
        prerequisites: ["EE 4141"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4242",
        prerequisites: [],
        coRequisites: ["EE 4241"],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4243",
        prerequisites: [],
        coRequisites: ["EE 4241"],
        type: "regular",
      },
      {
        subjectCode: "EE 4244",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4246",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Operation and Control",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4247",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Protection II (Lighting Protection and Grounding)",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4248",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Transmission Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4249",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Programmable Logic Controllers in Manufacturing & Power System",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4250",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Solar and Biomass Energy",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4251",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Sales and Marketing Management",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 5,
    creditUnits: 14,
  },
  //FIRST YEAR - FIRST STEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1103",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 22,
  },
  // FIRST YEAR - SECOND SEM - REGULAR - OC

  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 12",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 24,
  },
  // FIRST YEAR - SUMMER - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE SocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 1,
    creditUnits: 9,
  },
  // SECOND YEAR - FIRST SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201", "EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1020",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2142",
        prerequisites: ["EMath 1201", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ME 2143",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Fil 13",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 3a",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 25,
  },
  // SECOND YEAR - SECOND SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "EMath 2200",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1014",
        prerequisites: ["Engg 1012"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2241",
        prerequisites: ["EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2242",
        prerequisites: ["EE 2141"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 2243",
        prerequisites: ["EMath 2101", "Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 2241",
        prerequisites: ["EE 2142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ME 2243",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 24,
  },
  // SECOND YEAR - SUMMER - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE SocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },
  // THIRD YEAR - FIRST SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "EE 3141",
        prerequisites: ["EE 2242", "EE 2243"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3142",
        prerequisites: [],
        coRequisites: ["EE 3141"],
        type: "regular",
      },
      {
        subjectCode: "EE 3143",
        prerequisites: ["EE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3144",
        prerequisites: ["GESocSci 5"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3145",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3141",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3142",
        prerequisites: [],
        coRequisites: ["ECE 3141"],
        type: "regular",
      },
      {
        subjectCode: "ECE 3143",
        prerequisites: ["ECE 2241"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 21,
  },
  // THIRD YEAR - SECOND SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "Engg 1023",
        prerequisites: ["Engg 1001", "Engg 1014"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3241",
        prerequisites: ["EE 3141", "EE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3242",
        prerequisites: ["EE 2242"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3243",
        prerequisites: ["EE 2241", "ECE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 3244",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3241",
        prerequisites: ["ECE 3141", "ECE 3142"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "ECE 3242",
        prerequisites: [],
        coRequisites: ["ECE 3241"],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 22,
  },
  // THIRD YEAR - SUMMER - REGULAR - NC
  {
    subjects: [
      {
        subjectCode: "EE 3341",
        prerequisites: [],
        coRequisites: [],
        name: "EE On-the-Job Training",
        units: 2,
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 3,
    creditUnits: 3,
  },
  // FOURTH YEAR - FIRST SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "EE 4140",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4141",
        prerequisites: ["EE 3144"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4142",
        prerequisites: ["EE 3241"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4143",
        prerequisites: ["EE 3243"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4144",
        prerequisites: ["EE 3244"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4145",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4146",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Planning",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4147",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Protection I (Protective Relaying)",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4148",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Distribution Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4149",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Pneumatics & Process Control",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4150",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Wind and Hydro Energy",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4151",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Projecting Testing Design & Documentation",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 17,
  },
  // FOURTH - SECOND SEM - REGULAR - OC
  {
    subjects: [
      {
        subjectCode: "EE 4240",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4241",
        prerequisites: ["EE 4141"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EE 4242",
        prerequisites: [],
        coRequisites: ["EE 4241"],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4243",
        prerequisites: [],
        coRequisites: ["EE 4241"],
        type: "regular",
      },
      {
        subjectCode: "EE 4244",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
      {
        subjectCode: "EE 4246",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Operation and Control",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4247",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Power System Protection II (Lighting Protection and Grounding)",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4248",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Transmission Design",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4249",
        referenceCode: "EE TE 2",
        prerequisites: [],
        coRequisites: [],
        name: "Programmable Logic Controllers in Manufacturing & Power System",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4250",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Solar and Biomass Energy",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
      {
        subjectCode: "EE 4251",
        referenceCode: "EE TE 1",
        prerequisites: [],
        coRequisites: [],
        name: "Sales and Marketing Management",
        units: 4,
        yearStanding: 4,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 14,
  },
];
