import { DependencyListV2 } from "./types";

// OLD CURRICULUM 2018

export const pkgeDepOld: DependencyListV2 = [
  {
    // B - 1yr - 1sem - oc
    subjects: [
      {
        subjectCode: "EBMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBMath 1102",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 23,
  },

  // B - 1yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "EBMath 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBEngg 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE1a(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE2B(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 26,
  },
  // B - 2yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1004",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GE Eng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 21,
  },
  // B - 2yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1002",
        prerequisites: ["EMath 1101", "PkgE 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1003",
        prerequisites: ["PkgE 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 23,
  },
  // B - 3yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201", "EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1033",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1004",
        prerequisites: ["GEHum 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1005",
        prerequisites: ["PkgE 1002", "PkgE 1003"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Chem 3d",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Advert 121",
        prerequisites: [],
        coRequisites: ["PkgE 1004"],
        type: "regular",
      },
      {
        subjectCode: "PE 3a",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 25,
  },
  // B - 3yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "ME 1000",
        prerequisites: ["Engg 1004"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1007",
        prerequisites: ["PkgE 1005", "Chem 3d"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1008",
        prerequisites: ["Engg 1033"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1009",
        prerequisites: ["PkgE 1004"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1010",
        prerequisites: ["Advert 121"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 21,
  },
  // B - 4yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1011",
        prerequisites: ["PkgE 1007"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1012",
        prerequisites: ["Engg 1012", "PkgE 1007"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1013",
        prerequisites: ["GESocSci 5", "PkgE 1007"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1014",
        prerequisites: ["ME 1000"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1015",
        prerequisites: ["PkgE 1008"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1016",
        prerequisites: [],
        coRequisites: ["PkgE 1012"],
        type: "regular",
      },
      {
        subjectCode: "Fil 12",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1025",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Food Packaging",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1027",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Packaging Production Management",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1029",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Packaging Creatives and Invention Process",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1031",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Technopreneurship 102",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 25,
  },
  // B - 4yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1017",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1018",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1019",
        prerequisites: ["PkgE 1007", "EMath 2101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1020",
        prerequisites: ["PkgE 1012"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1021",
        prerequisites: ["PkgE 1016"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1022",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "Fil 13",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },

      {
        subjectCode: "PkgE 1026",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Pharmaceutical Packaging",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1028",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Supply Chain Management",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1030",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Packaging Art and Structural Designs",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1032",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Technopreneurship 103",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 27,
  },
  // B - 5yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "PkgE 1023",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 5,
    creditUnits: 5,
  },
  // B - 5yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "PkgE 1024",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 5,
    creditUnits: 5,
  },
  // R - 1yr - 1sem - oc

  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1004",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 24,
  },
  // R - 1yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1002",
        prerequisites: ["PkgE 1001", "EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1003",
        prerequisites: ["PkgE 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 1a(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 2B(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 26,
  },
  // R - 1yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 1,
    creditUnits: 9,
  },

  // R - 2yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201", "EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1033",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1004",
        prerequisites: ["GEHum 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1005",
        prerequisites: ["PkgE 1002", "PkgE 1003"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Chem 3d",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Advert 121",
        prerequisites: [],
        coRequisites: ["PkgE 1004"],
        type: "regular",
      },
      {
        subjectCode: "PE 3a",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 25,
  },
  // R - 2yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "ME 1000",
        prerequisites: ["Engg 1004"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1007",
        prerequisites: ["PkgE 1005", "Chem 3d"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1008",
        prerequisites: ["Engg 1033"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1009",
        prerequisites: ["PkgE 1004"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1010",
        prerequisites: ["Advert 121"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a(M)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PE 4a(W)",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 27,
  },
  // R - 2yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },
  // R - 3yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1025",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1011",
        prerequisites: ["PkgE 1007"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1012",
        prerequisites: ["PkgE 1007", "Engg 1012"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1013",
        prerequisites: ["PkgE 1007", "GESocSci 5"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1014",
        prerequisites: ["ME 1000"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1015",
        prerequisites: ["PkgE 1008"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1016",
        prerequisites: [],
        coRequisites: ["PkgE 1012"],
        type: "regular",
      },
      {
        subjectCode: "Fil 12",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },

      {
        subjectCode: "PkgE 1025",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Food Packaging",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1027",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Packaging Production Management",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1029",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Packaging Creatives and Invention Process",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1031",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Technopreneurship 102",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 25,
  },
  // R - 3yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "Engg 1027",
        prerequisites: ["Engg 1025"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1017",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1018",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1019",
        prerequisites: ["PkgE 1007", "EMath 2101"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 1020",
        prerequisites: ["PkgE 1012"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1021",
        prerequisites: ["PkgE 1016"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1026",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Pharmaceutical Packaging",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1028",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Supply Chain Management",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1030",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Packaging Art and Structural Designs",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1032",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Technopreneurship 103",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 1022",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 24,
  },
  // R - 3yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 3,
    creditUnits: 3,
  },
  // R - 4yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "PkgE 1023",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 5,
  },
  // R - 4yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "PkgE 1024",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 5,
  },
];

// NEW CURRICULUM

export const pkgeDepNew: DependencyListV2 = [
  {
    // B - 1yr - 1sem - nc
    subjects: [
      {
        subjectCode: "EBMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBMath 1102",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 23,
  },
  // B - 1yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "EBMath 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EBEngg 1201",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: ["NSTP1-CWTS"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: ["NSTP1-LTS"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: ["NSTP1-ROTC"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PEATHFit2 W",
        prerequisites: ["PATHFit1 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 M",
        prerequisites: ["PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 26,
  },
  // B - 2yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1004",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1111",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CETech1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CESocSci3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 23,
  },
  // B - 2yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1211",
        prerequisites: ["EMath 1101", "PkgE 1111"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1212",
        prerequisites: ["PkgE 1111"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 23,
  },
  // B - 3yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201", "EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1036",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "PkgE 2111",
        prerequisites: ["GEHum 1", "PkgE 1111"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2112",
        prerequisites: ["PkgE 1211", "PkgE 1003"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2113",
        prerequisites: ["GESocSci 5"],
        coRequisites: ["PkgE 2111"],
        type: "regular",
      },
      {
        subjectCode: "Chem 3005",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 25,
  },
  // B - 3yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2211",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2212",
        prerequisites: ["PkgE 2112", "Chem 3005"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2213",
        prerequisites: ["Engg 1032"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2214",
        prerequisites: ["PkgE 2111"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2215",
        prerequisites: [],
        coRequisites: ["PkgE 2213"],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2216",
        prerequisites: ["PkgE 2111"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1036"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 24,
  },
  // B - 3yr - summer - nc
  {
    subjects: [
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1037",
        prerequisites: ["Engg 1036"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2311",
        prerequisites: ["PkgE 2212", "Engg 1019"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SUMMER",
    yearLevel: 3,
    creditUnits: 9,
  },
  // B - 4yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "PkgE 3111",
        prerequisites: ["PkgE 2212"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3112",
        prerequisites: ["Engg 1012", "PkgE 2212"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3113",
        prerequisites: [],
        coRequisites: ["PkgE 3112"],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3114",
        prerequisites: ["PkgE 2215"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3115",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Food Packaging",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3116",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Packaging Production Management",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3117",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Packaging Creatives and Invention Process",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3118",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Technopreneurship 102",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 13,
  },

  // B - 4yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 3211",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 3212",
        prerequisites: ["PkgE 3112"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3213",
        prerequisites: ["PkgE 3113"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3214",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 3215",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Pharmaceutical Packaging",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3216",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Supply Chain Management",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3217",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Packaging Art and Structural Designs",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3218",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Technopreneurship 103",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 16,
  },
  // B - 5yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "PkgE 4111",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "FIRST",
    yearLevel: 5,
    creditUnits: 5,
  },
  // B - 5yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "PkgE 4211",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Bridging",
    semesterType: "SECOND",
    yearLevel: 5,
    creditUnits: 5,
  },
  // R - 1yr - 1sem - oc

  {
    subjects: [
      {
        subjectCode: "EMath 1101",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1001",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1002",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1111",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEMath 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1004",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP1-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit1 M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 1,
    creditUnits: 24,
  },
  // R - 1yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 1201",
        prerequisites: ["EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "EMath 1202",
        prerequisites: ["EMath 1101", "GEMath 1"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1006",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1009",
        prerequisites: [],
        coRequisites: ["EMath 1201"],
        type: "regular",
      },
      {
        subjectCode: "Engg 1011",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1211",
        prerequisites: ["PkgE 1111", "EMath 1101"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 1212",
        prerequisites: ["PkgE 1111"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-CWTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-LTS",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "NSTP2-ROTC",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 W",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit2 M",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "RE 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "SEAL 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 1,
    creditUnits: 27,
  },
  // R - 1yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "GESocSci 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GEHum 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 5",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 1,
    creditUnits: 9,
  },
  // R - 2yr - 1sem - oc
  {
    subjects: [
      {
        subjectCode: "EMath 2101",
        prerequisites: ["EMath 1201"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1012",
        prerequisites: ["Engg 1009"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1036",
        prerequisites: ["EMath 1202"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2111",
        prerequisites: ["GEHum 1", "Pkge 1111"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2112",
        prerequisites: ["PkgE 1211"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2113",
        prerequisites: ["GESocSci 5"],
        coRequisites: ["PkgE 2111"],
        type: "regular",
      },
      {
        subjectCode: "Chem 3005",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CELit 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit3 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 2,
    creditUnits: 27,
  },
  // R - 2yr - 2sem - oc
  {
    subjects: [
      {
        subjectCode: "PkgE 2211",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2212",
        prerequisites: ["PkgE 2212", "Chem 3005"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2213",
        prerequisites: [],
        coRequisites: ["Engg 1032"],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2214",
        prerequisites: ["PkgE 2111"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2215",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 2,
        type: "regular",
      },
      {
        subjectCode: "PkgE 2216",
        prerequisites: ["PkgE 2111"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1032",
        prerequisites: ["Engg 1036"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1019",
        prerequisites: ["Engg 1001"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "GESocSci 6",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 W",
        prerequisites: ["PATHFit1 W", "PATHFit2 W"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PATHFit4 M",
        prerequisites: ["PATHFit1 M", "PATHFit2 M"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 2,
    creditUnits: 29,
  },
  // R - 2yr - summer - oc
  {
    subjects: [
      {
        subjectCode: "GEEng 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "Engg 1037",
        prerequisites: ["Engg 1036"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 2311",
        prerequisites: ["PkgE 2212", "Engg 1019"],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 2,
    creditUnits: 9,
  },
  // R - 3yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "GESocSci 2",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3111",
        prerequisites: ["PkgE 2212"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3112",
        prerequisites: ["PkgE 2212", "Engg 1012"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3113",
        prerequisites: [],
        coRequisites: ["PkgE 3112"],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3114",
        prerequisites: ["PkgE 2215"],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },

      {
        subjectCode: "PkgE 3115",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Food Packaging",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3116",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Packaging Production Management",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3117",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Packaging Creatives and Invention Process",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3118",
        referenceCode: "PkgE TE 1",
        prerequisites: [],
        name: "Technopreneurship 102",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 3,
    creditUnits: 19,
  },
  // R - 3yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "Engg 1030",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 3211",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 3212",
        prerequisites: ["PkgE 3112"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 3213",
        prerequisites: ["PkgE 3113"],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "PkgE 3214",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 3,
        type: "regular",
      },
      {
        subjectCode: "GESocSci 4",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "PkgE 3215",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Pharmaceutical Packaging",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3216",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Supply Chain Management",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3217",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Packaging Art and Structural Designs",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
      {
        subjectCode: "PkgE 3218",
        referenceCode: "PkgE TE 2",
        prerequisites: [],
        name: "Technopreneurship 103",
        units: 3,
        coRequisites: [],
        yearStanding: 3,
        type: "elective",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 3,
    creditUnits: 19,
  },
  // R - 3yr - summer - nc
  {
    subjects: [
      {
        subjectCode: "GESocSci 3",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
      {
        subjectCode: "CETech 1",
        prerequisites: [],
        coRequisites: [],
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SUMMER",
    yearLevel: 3,
    creditUnits: 6,
  },
  // R - 4yr - 1sem - nc
  {
    subjects: [
      {
        subjectCode: "PkgE 4111",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "FIRST",
    yearLevel: 4,
    creditUnits: 5,
  },
  // R - 4yr - 2sem - nc
  {
    subjects: [
      {
        subjectCode: "PkgE 4211",
        prerequisites: [],
        coRequisites: [],
        yearStanding: 4,
        type: "regular",
      },
    ],
    enrollmentType: "Regular",
    semesterType: "SECOND",
    yearLevel: 4,
    creditUnits: 5,
  },
];
